"""add_launch_modules_library_chat_audit

Revision ID: 4a9f8b2c1d3e
Revises: cdbd1e0
Create Date: 2024-10-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a9f8b2c1d3e'
down_revision = 'cdbd1e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Library Module Tables
    op.create_table('authors',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('bio', sa.Text(), nullable=True),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_institution_id'), 'authors', ['institution_id'], unique=False)

    op.create_table('publishers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publishers_institution_id'), 'publishers', ['institution_id'], unique=False)

    op.create_table('books',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('isbn', sa.String(), nullable=True),
        sa.Column('author_id', sa.String(), nullable=False),
        sa.Column('publisher_id', sa.String(), nullable=True),
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('rack_number', sa.String(), nullable=True),
        sa.Column('total_copies', sa.Integer(), default=1),
        sa.Column('available_copies', sa.Integer(), default=1),
        sa.Column('price', sa.Numeric(10, 2), nullable=True),
        sa.Column('purchase_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(), default='AVAILABLE'), # AVAILABLE, ISSUED, LOST
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
        sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_institution_id'), 'books', ['institution_id'], unique=False)
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)

    op.create_table('library_fine_config',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('fine_per_day', sa.Numeric(10, 2), default=5.0),
        sa.Column('max_fine_cap', sa.Numeric(10, 2), default=500.0),
        sa.Column('loan_period_days', sa.Integer(), default=14),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('institution_id')
    )

    op.create_table('book_issues',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('book_id', sa.String(), nullable=False),
        sa.Column('student_id', sa.String(), nullable=False),
        sa.Column('issue_date', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('due_date', sa.DateTime(), nullable=False),
        sa.Column('return_date', sa.DateTime(), nullable=True),
        sa.Column('fine_amount', sa.Numeric(10, 2), default=0.0),
        sa.Column('status', sa.String(), default='ISSUED'), # ISSUED, RETURNED, OVERDUE
        sa.Column('issued_by', sa.String(), nullable=False),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_issues_status'), 'book_issues', ['status'], unique=False)

    # 2. Chat & Notification Tables
    op.create_table('chat_messages',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('sender_id', sa.String(), nullable=False),
        sa.Column('receiver_id', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('file_url', sa.String(), nullable=True),
        sa.Column('is_read', sa.Boolean(), default=False),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('sent_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_receiver_id'), 'chat_messages', ['receiver_id'], unique=False)

    op.create_table('notifications',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('type', sa.String(), nullable=False), # FEE, ATTENDANCE, EXAM, GENERAL
        sa.Column('channel', sa.String(), nullable=False), # IN_APP, SMS, EMAIL, WHATSAPP
        sa.Column('is_sent', sa.Boolean(), default=False),
        sa.Column('is_read', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)

    # 3. Audit Trail Table (God Mode)
    op.create_table('audit_logs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('action', sa.String(), nullable=False), # CREATE, UPDATE, DELETE, LOGIN
        sa.Column('entity_type', sa.String(), nullable=False), # STUDENT, FEE, USER
        sa.Column('entity_id', sa.String(), nullable=True),
        sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('user_agent', sa.String(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.func.now()),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity'), 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)

    # 4. Theme Customization Table
    op.create_table('institution_themes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('institution_id', sa.String(), nullable=False),
        sa.Column('primary_color', sa.String(), default='#3B82F6'),
        sa.Column('secondary_color', sa.String(), default='#1E40AF'),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('favicon_url', sa.String(), nullable=True),
        sa.Column('font_family', sa.String(), default='Inter'),
        sa.Column('layout_mode', sa.String(), default='SIDEBAR'), # SIDEBAR, TOPNAV
        sa.Column('is_active', sa.Boolean(), default=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('institution_id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution_themes')
    op.drop_table('audit_logs')
    op.drop_table('notifications')
    op.drop_table('chat_messages')
    op.drop_table('book_issues')
    op.drop_table('library_fine_config')
    op.drop_table('books')
    op.drop_table('publishers')
    op.drop_table('authors')
    # ### end Alembic commands ###
